# Generated by Django 5.2.1 on 2025-05-26 02:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Objetivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('nivel', models.CharField(choices=[('saludable', 'Saludable'), ('adelgazamiento', 'Adelgazamiento'), ('fuerza', 'Fuerza'), ('resistencia', 'Resistencia'), ('hipertrofia', 'Hipertrofia'), ('aumento_masa', 'Aumento de masa muscular'), ('estético', 'Estético'), ('culturismo', 'Culturismo')], max_length=50)),
                ('descripcion', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Ejercicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('grupo_muscular', models.CharField(max_length=50)),
                ('nivel', models.CharField(choices=[('principiante', 'Principiante'), ('intermedio', 'Intermedio'), ('avanzado', 'Avanzado')], max_length=20)),
                ('duracion', models.IntegerField(help_text='Duración en segundos')),
                ('tipo', models.CharField(max_length=30)),
                ('instrucciones', models.TextField()),
                ('video_url', models.URLField(blank=True, null=True)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ejercicios', to='PowerZone.categoria')),
            ],
        ),
        migrations.CreateModel(
            name='PlanAlimentacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
                ('calorias_dia', models.IntegerField()),
                ('duracion_dias', models.IntegerField()),
                ('objetivo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='PowerZone.objetivo')),
            ],
        ),
        migrations.CreateModel(
            name='Rutina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('duracion_total', models.IntegerField(blank=True, help_text='Duración total en minutos', null=True)),
                ('ejercicios', models.ManyToManyField(to='PowerZone.ejercicio')),
                ('objetivo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='PowerZone.objetivo')),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('edad', models.IntegerField()),
                ('peso', models.FloatField()),
                ('altura', models.FloatField()),
                ('objetivo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='PowerZone.objetivo')),
                ('plan_alimentacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='PowerZone.planalimentacion')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
