# Generated by Django 5.2.1 on 2025-06-02 18:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PowerZone', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ejercicio',
            name='categoria',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='objetivo',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='plan_alimentacion',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='user',
        ),
        migrations.RemoveField(
            model_name='ejercicio',
            name='duracion',
        ),
        migrations.RemoveField(
            model_name='ejercicio',
            name='instrucciones',
        ),
        migrations.RemoveField(
            model_name='ejercicio',
            name='nivel',
        ),
        migrations.RemoveField(
            model_name='ejercicio',
            name='tipo',
        ),
        migrations.RemoveField(
            model_name='ejercicio',
            name='video_url',
        ),
        migrations.RemoveField(
            model_name='objetivo',
            name='nivel',
        ),
        migrations.RemoveField(
            model_name='planalimentacion',
            name='calorias_dia',
        ),
        migrations.RemoveField(
            model_name='planalimentacion',
            name='duracion_dias',
        ),
        migrations.RemoveField(
            model_name='planalimentacion',
            name='nombre',
        ),
        migrations.RemoveField(
            model_name='rutina',
            name='duracion_total',
        ),
        migrations.RemoveField(
            model_name='rutina',
            name='ejercicios',
        ),
        migrations.AddField(
            model_name='ejercicio',
            name='descripcion',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ejercicio',
            name='rutina',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ejercicios', to='PowerZone.rutina'),
        ),
        migrations.AddField(
            model_name='rutina',
            name='descripcion',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='objetivo',
            name='descripcion',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='planalimentacion',
            name='objetivo',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='plan_alimentacion', to='PowerZone.objetivo'),
        ),
        migrations.AlterField(
            model_name='rutina',
            name='objetivo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rutinas', to='PowerZone.objetivo'),
        ),
        migrations.DeleteModel(
            name='Categoria',
        ),
        migrations.DeleteModel(
            name='Usuario',
        ),
    ]
