# Generated by Django 5.2.1 on 2025-06-02 19:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PowerZone', '0002_remove_ejercicio_categoria_remove_usuario_objetivo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='planalimentacion',
            name='nombre',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='planalimentacion',
            name='descripcion',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='planalimentacion',
            name='objetivo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='planes_alimentacion', to='PowerZone.objetivo'),
        ),
    ]
