# Generated by Django 5.2.1 on 2025-06-02 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PowerZone', '0003_planalimentacion_nombre_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ejercicio',
            name='descripcion',
            field=models.TextField(blank=True, help_text='Descripción breve del ejercicio', null=True),
        ),
        migrations.AlterField(
            model_name='ejercicio',
            name='grupo_muscular',
            field=models.CharField(help_text='Ej: Piernas, Espalda, Pecho, etc', max_length=50),
        ),
        migrations.AlterField(
            model_name='ejercicio',
            name='nombre',
            field=models.CharField(help_text='Ej: Sentadillas', max_length=100),
        ),
        migrations.AlterField(
            model_name='objetivo',
            name='descripcion',
            field=models.TextField(blank=True, help_text='Descripción breve del objetivo', null=True),
        ),
        migrations.AlterField(
            model_name='objetivo',
            name='nombre',
            field=models.CharField(help_text='Ej: Ganar masa muscular', max_length=100),
        ),
        migrations.AlterField(
            model_name='planalimentacion',
            name='descripcion',
            field=models.TextField(blank=True, help_text='Descripción breve del plan de alimentación', null=True),
        ),
        migrations.AlterField(
            model_name='planalimentacion',
            name='nombre',
            field=models.CharField(blank=True, help_text='Ej: Plan de alimentación para volumen', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='rutina',
            name='descripcion',
            field=models.TextField(blank=True, help_text='Descripción breve de la rutina', null=True),
        ),
        migrations.AlterField(
            model_name='rutina',
            name='nombre',
            field=models.CharField(help_text='Ej: Rutina de fuerza', max_length=100),
        ),
    ]
