# Generated by Django 5.2.1 on 2025-06-05 22:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PowerZone', '0004_alter_ejercicio_descripcion_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PesoIdeal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('peso', models.DecimalField(decimal_places=2, max_digits=5)),
                ('estatura', models.DecimalField(decimal_places=2, max_digits=4)),
                ('edad', models.PositiveIntegerField()),
                ('fotos', models.ImageField(blank=True, null=True, upload_to='fotos/')),
                ('horas_sueno', models.DecimalField(decimal_places=1, max_digits=3)),
                ('dieta', models.TextField()),
            ],
        ),
        migrations.RemoveField(
            model_name='ejercicio',
            name='nombre',
        ),
        migrations.RemoveField(
            model_name='ejercicio',
            name='rutina',
        ),
        migrations.RemoveField(
            model_name='planalimentacion',
            name='descripcion',
        ),
        migrations.RemoveField(
            model_name='planalimentacion',
            name='nombre',
        ),
        migrations.RemoveField(
            model_name='rutina',
            name='descripcion',
        ),
        migrations.RemoveField(
            model_name='rutina',
            name='nombre',
        ),
        migrations.AddField(
            model_name='ejercicio',
            name='duracion',
            field=models.PositiveIntegerField(default=30, help_text='Duración en minutos'),
        ),
        migrations.AddField(
            model_name='ejercicio',
            name='gif',
            field=models.ImageField(blank=True, null=True, upload_to='ejercicios/'),
        ),
        migrations.AddField(
            model_name='ejercicio',
            name='usa_mancuernas',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='planalimentacion',
            name='calorias_dia',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='planalimentacion',
            name='proteinas_dia',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='rutina',
            name='comidas_dia',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='rutina',
            name='tipo_entrenamiento',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='rutina',
            name='veces_entrenar_dia',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='rutina',
            name='veces_entrenar_semana',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ejercicio',
            name='descripcion',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ejercicio',
            name='grupo_muscular',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='objetivo',
            name='descripcion',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='objetivo',
            name='nombre',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='planalimentacion',
            name='objetivo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='planes', to='PowerZone.objetivo'),
        ),
    ]
