# Generated by Django 5.2.1 on 2025-06-30 20:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PowerZone', '0005_pesoideal_remove_ejercicio_nombre_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alimento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('calorias_por_100g', models.FloatField(blank=True, null=True)),
                ('proteinas_por_100g', models.FloatField(blank=True, null=True)),
                ('grasas_por_100g', models.FloatField(blank=True, null=True)),
                ('carbohidratos_por_100g', models.FloatField(blank=True, null=True)),
                ('nota', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='detallePlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad_gramos', models.FloatField(blank=True, null=True)),
                ('momento_dia', models.CharField(blank=True, choices=[('desayuno', 'Desayuno'), ('almuerzo', 'Almuerzo'), ('cena', 'Cena')], max_length=20, null=True)),
                ('alimento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='PowerZone.alimento')),
                ('plan_alimentacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='PowerZone.planalimentacion')),
            ],
        ),
    ]
