# Generated by Django 5.2.1 on 2025-06-30 21:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PowerZone', '0006_alimento_detalleplan'),
    ]

    operations = [
        migrations.AddField(
            model_name='ejercicio',
            name='peso_ideal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ejercicios_recomendados', to='PowerZone.pesoideal'),
        ),
    ]
