# Generated by Django 5.2.1 on 2025-06-30 21:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PowerZone', '0007_ejercicio_peso_ideal'),
    ]

    operations = [
        migrations.RenameField(
            model_name='detalleplan',
            old_name='cantidad_gramos',
            new_name='cantidad_proteina_gramos',
        ),
    ]
