# Generated by Django 5.2.1 on 2025-06-30 23:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PowerZone', '0008_rename_cantidad_gramos_detalleplan_cantidad_proteina_gramos'),
    ]

    operations = [
        migrations.CreateModel(
            name='PesoIdealHombre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estatura_min', models.DecimalField(blank=True, decimal_places=2, help_text='Estatura mínima en cm', max_digits=4, null=True)),
                ('estatura_max', models.DecimalField(blank=True, decimal_places=2, help_text='Estatura máxima en cm', max_digits=4, null=True)),
                ('edad', models.PositiveIntegerField(blank=True, help_text='Edad en años', null=True)),
                ('peso_min', models.DecimalField(blank=True, decimal_places=2, help_text='Peso mínimo en kg', max_digits=5, null=True)),
                ('peso_max', models.DecimalField(blank=True, decimal_places=2, help_text='Peso máximo en kg', max_digits=5, null=True)),
                ('fotos', models.ImageField(blank=True, null=True, upload_to='fotos/')),
                ('horas_sueno', models.DecimalField(decimal_places=1, max_digits=3)),
                ('dieta', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='PesoIdealMujer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estatura_min', models.DecimalField(blank=True, decimal_places=2, help_text='Estatura mínima en cm', max_digits=4, null=True)),
                ('estatura_max', models.DecimalField(blank=True, decimal_places=2, help_text='Estatura máxima en cm', max_digits=4, null=True)),
                ('edad', models.PositiveIntegerField(blank=True, help_text='Edad en años', null=True)),
                ('peso_min', models.DecimalField(blank=True, decimal_places=2, help_text='Peso mínimo en kg', max_digits=5, null=True)),
                ('peso_max', models.DecimalField(blank=True, decimal_places=2, help_text='Peso máximo en kg', max_digits=5, null=True)),
                ('fotos', models.ImageField(blank=True, null=True, upload_to='fotos/')),
                ('horas_sueno', models.DecimalField(decimal_places=1, max_digits=3)),
                ('dieta', models.TextField()),
            ],
        ),
        migrations.RemoveField(
            model_name='ejercicio',
            name='peso_ideal',
        ),
        migrations.AddField(
            model_name='ejercicio',
            name='peso_ideal_hombre',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ejercicios_recomendados', to='PowerZone.pesoidealhombre'),
        ),
        migrations.AddField(
            model_name='ejercicio',
            name='peso_ideal_mujer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ejercicios_recomendados', to='PowerZone.pesoidealmujer'),
        ),
        migrations.DeleteModel(
            name='PesoIdeal',
        ),
    ]
